server:
  port: 8080
spring:
  application:
    name: jia

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
        properties:
          hibernate:
            hbm2ddl:
              auto: update
